package shell

import (
	"fmt"

	"github.com/abiosoft/ishell"
)

func helpCmd(shell *ishell.Shell, ctx *ShellCtxt) *ishell.Cmd {
	return &ishell.Cmd{
		Name: "help",
		Help: "Show help, or help about a command (e.g. 'help put')",
		Func: func(c *ishell.Context) {
			if len(c.Args) == 0 {
				// list available commands with short help in the order they were registered
				fmt.Printf("\nCommands:\n")

				for _, cmd := range ctx.commands {
					fmt.Printf("  %12s\t%s\n%12s\t%s\n", cmd.Name, cmd.Help, "", cmd.LongHelp)
				}

				fmt.Printf("\nUse 'help <command>' to get more information about a command.\n\n")
			} else {
				// Invoke '<cmd> -h' to show autogenerated flag usage,
				// but only for commands registered in this shell.
				// This means that ishell builtins (e.g. "clear") don't get help text.
				args := []string{c.Args[0], "--help"}
				cmdFound := false
				for _, cmd := range ctx.commands {
					if cmd.Name == c.Args[0] {
						cmdFound = true
						break
					}
				}
				if !cmdFound {
					fmt.Printf("Unknown command: %s\n", c.Args[0])
					return
				}
				if err := shell.Process(args...); err != nil {
					c.Err(err)
				}
			}
		},
	}
}
