package shell

import (
	"bytes"
	"strings"

	"github.com/abiosoft/ishell"
	"github.com/ogier/pflag"
)

// formatFlagUsage tidies autogenerated flag usage:
// - strips the leading "Usage of <cmd>:" header pflag emits
// - removes the "=false" default markers
// - replaces ": " with a tab for alignment
func formatFlagUsage(usage string) string {
	// Remove the first line if it's the autogenerated header
	lines := strings.Split(usage, "\n")
	if len(lines) > 0 && strings.HasPrefix(lines[0], "Usage of ") {
		lines = lines[1:]
	}

	s := strings.Join(lines, "\n")
	s = strings.TrimLeft(s, "\n")
	s = strings.ReplaceAll(s, "=false", "")
	s = strings.ReplaceAll(s, ": ", ":\t")
	return s
}

// processFlagSet parses args using the provided FlagSet, captures the
// autogenerated usage and prints a tidy help message if -h/--help was
// requested. Returns true if parsing succeeded and the caller should
// continue, or false if the caller should return.
func processFlagSet(fs *pflag.FlagSet, usageHeader string, args []string, c *ishell.Context) bool {
	var buf bytes.Buffer
	fs.SetOutput(&buf)
	if err := fs.Parse(args); err != nil {
		if err == pflag.ErrHelp {
			// Ensure a blank line between header and flags
			c.Println(usageHeader + "\n\n" + formatFlagUsage(buf.String()))
			return false
		}
		c.Err(err)
		return false
	}
	return true
}

// checkHelp inspects args for -h/--help and prints usageHeader if present.
// Returns true if help was handled and the caller should return.
func checkHelp(usageHeader string, args []string, c *ishell.Context) bool {
	for _, a := range args {
		if a == "-h" || a == "--help" {
			if usageHeader != "" {
				c.Println(usageHeader)
			}
			return true
		}
	}
	return false
}
