name: Release

on:
  push:
    tags:
        - v*

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.23.1
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.1
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - run: echo "VERSION=`echo $(git describe --tags)`" >> $GITHUB_ENV

      - name: Build Linux AMD64 binary
        run: GOOS=linux GOARCH=amd64 go build -v -ldflags "-X 'github.com/juruen/rmapi/version.Version=${{ env.VERSION }}'" -o rmapi-linux-amd64 .

      - name: Build Linux ARM64 binary
        run: GOOS=linux GOARCH=arm64 go build -v -ldflags "-X 'github.com/juruen/rmapi/version.Version=${{ env.VERSION }}'" -o rmapi-linux-arm64 .

      - name: Create Linux AMD64 tar
        run: tar czvf rmapi-linux-amd64.tar.gz rmapi-linux-amd64

      - name: Create Linux ARM64 tar
        run: tar czvf rmapi-linux-arm64.tar.gz rmapi-linux-arm64

      - name: Build MacOS AMD64 binary
        run: GOOS=darwin GOARCH=amd64 go build -v -ldflags "-X 'github.com/juruen/rmapi/version.Version=${{ env.VERSION }}'" -o rmapi-darwin-amd64 .

      - name: Build MacOS ARM64 binary
        run: GOOS=darwin GOARCH=arm64 go build -v -ldflags "-X 'github.com/juruen/rmapi/version.Version=${{ env.VERSION }}'" -o rmapi-darwin-arm64 .

      - name: Create MacOS AMD64 zip
        run: zip rmapi-darwin-amd64.zip rmapi-darwin-amd64

      - name: Create MacOS ARM64 zip
        run: zip rmapi-darwin-arm64.zip rmapi-darwin-arm64

      - name: Build Windows AMD64 binary
        run: GOOS=windows GOARCH=amd64 go build -v -ldflags "-X 'github.com/juruen/rmapi/version.Version=${{ env.VERSION }}'" -o rmapi-windows-amd64.exe .

      - name: Build Windows ARM64 binary
        run: GOOS=windows GOARCH=arm64 go build -v -ldflags "-X 'github.com/juruen/rmapi/version.Version=${{ env.VERSION }}'" -o rmapi-windows-arm64.exe .

      - name: Create Windows AMD64 zip
        run: zip rmapi-windows-amd64.zip rmapi-windows-amd64.exe

      - name: Create Windows ARM64 zip
        run: zip rmapi-windows-arm64.zip rmapi-windows-arm64.exe

      - name: Release
        uses: docker://softprops/action-gh-release
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: rmapi-*.zip rmapi-*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
